import type { CourseLesson, CourseQuestion } from './course-types';

export const HISTORY_ALLOCATION_NOTE = 'History is organised by key stage in England’s National Curriculum. These Year 1–9 allocations are an editorial teaching sequence, not statutory year-by-year requirements. This 36-week programme uses six enquiries per topic; it needs a teacher’s review and local adaptation before use as a complete school scheme.';
export const HISTORY_CURRICULUM_SOURCE = 'https://www.gov.uk/government/publications/national-curriculum-in-england-history-programmes-of-study';

type Topic = {
  year: number; title: string; context: string; sequence: [string, string, string];
  clue: string; supports: string; limit: string; change: string; cause: string;
  word: [string, string]; source: string;
};
const EH = 'https://www.english-heritage.org.uk/learn/story-of-england/';
const NA = 'https://www.nationalarchives.gov.uk/education/';
const BM = 'https://www.britishmuseum.org/learn/schools/ages-7-11/';
const SM = 'https://www.sciencemuseum.org.uk/see-and-do/object-gallery';

// Original teaching summaries and explicitly described evidence types. No invented
// historical quotations or documents are presented as genuine primary sources.
const TOPICS: Topic[] = [
  { year:1,title:'My own history',context:'History explores what happened before now. Your own story has a beginning and events that happened in an order. Different families keep different kinds of memories, and nobody has to share a private photograph.',sequence:['being a baby','starting school','learning in school now'],clue:'A dated photograph of a child at a school entrance.',supports:'what that entrance looked like on that day',limit:'what every child felt at school',change:'a child grows and learns new skills',cause:'practice and help can build a new skill',word:['past','time before now'],source:HISTORY_CURRICULUM_SOURCE },
  { year:1,title:'Toys then and now',context:'Children played before electronic games existed. Dolls, balls and wooden toys appear in museum collections. Many old games still have living versions; the age of a toy does not tell us whether its owner enjoyed it.',sequence:['a toy made long ago','a grandparent playing as a child','a child choosing a toy today'],clue:'An old wooden toy with worn wheels.',supports:'the toy’s material and signs of use',limit:'the name of its owner without another record',change:'some toys gained electric motors or screens',cause:'new materials and inventions changed what makers could produce',word:['material','what something is made from'],source:SM },
  { year:1,title:'Homes and household objects',context:'Homes can show both change and continuity. People needed places to sleep, prepare food and stay warm in the past. Objects and old pictures help us explore these needs, but families did not all own the same things.',sequence:['a candle used before electric lighting','electric lights becoming available','lights used in homes today'],clue:'A museum candle holder made before electric lighting.',supports:'one way people could hold a candle',limit:'that every home used only candles',change:'electric lighting changed how many homes were lit',cause:'electricity networks made electric lights usable in more homes',word:['continuity','something that stays similar over time'],source:SM },
  { year:1,title:'Journeys in living memory',context:'Walking, cycling, buses and trains connect people with places. A grown-up may remember a different journey to school. Their memory is useful evidence about their life, but it cannot describe every person’s journey.',sequence:['an adult travelling to school as a child','that adult growing up','your journey to school now'],clue:'A grown-up’s account of walking to school when young.',supports:'a remembered journey in that person’s life',limit:'everyone’s usual way of travelling',change:'routes and vehicles can change while people still make journeys',cause:'new roads or transport services can change a route',word:['memory','something a person remembers'],source:SM },
  { year:1,title:'Sending messages',context:'People sent letters before telephones existed. Later, telephones carried voices, and computers helped people exchange digital messages. These methods overlap: a letter can still be used today, so new technology does not instantly replace everything.',sequence:['letters before telephones','early telephones','digital messages'],clue:'A rotary telephone in a museum collection.',supports:'how a user selected a telephone number',limit:'what a caller said without a recording',change:'some messages can now travel digitally',cause:'communication technology allowed new ways to send information',word:['communication','sharing information'],source:'https://blog.sciencemuseum.org.uk/information-age-10-years-on/' },
  { year:1,title:'Our local history trail',context:'A local place might contain an older building beside a newer one. Street names, maps and dated photographs can provide clues. An old-looking building is not automatically the oldest: people sometimes build in an older style.',sequence:['a building shown on an older dated map','the same place shown on a later map','the place today'],clue:'Two dated maps of the same street.',supports:'which buildings are marked on each map',limit:'what people inside those buildings thought',change:'a street may gain buildings while its route stays similar',cause:'new homes or services can change a neighbourhood',word:['local','near the place where you live'],source:'https://historicengland.org.uk/education/schools-resources/' },
  { year:2,title:'The Great Fire of London',context:'In September 1666 a fire began in a bakery in Pudding Lane. London’s closely packed buildings and windy conditions helped it spread. People escaped and the city was rebuilt; diaries and official records offer different kinds of evidence.',sequence:['London before September 1666','the Great Fire in September 1666','rebuilding after the fire'],clue:'A dated map showing the area damaged by the fire.',supports:'which area the mapmaker marked as damaged',limit:'how each Londoner felt during the fire',change:'rebuilding included rules intended to reduce fire risk',cause:'closely packed buildings and wind helped the fire spread',word:['rebuild','build again after damage'],source:NA+'teaching-resources/great-fire-of-london-impact/' },
  { year:2,title:'Florence Nightingale and nursing',context:'Florence Nightingale worked with a team of nurses during the Crimean War. She later argued for better hospital conditions and used numbers to explain problems. Nurses and other helpers contributed too; change was not the work of one person alone.',sequence:['Nightingale’s early life','her nursing work in the Crimean War','her later work to improve hospitals'],clue:'Nightingale’s hospital reports containing numbers.',supports:'the conditions she recorded and argued about',limit:'everything every patient experienced',change:'hospital care and nurse training developed over time',cause:'evidence about poor conditions helped arguments for improvements',word:['nurse','a person trained to care for people who are ill'],source:NA+'resources/florence-nightingale/' },
  { year:2,title:'Mary Anning’s fossil clues',context:'Mary Anning collected fossils near Lyme Regis in the nineteenth century. Her careful discoveries helped people study animals from the distant past. Scientists did not always give her fair recognition, and her story helps us ask whose work gets remembered.',sequence:['Anning’s childhood','her fossil discoveries','museum study of those fossils today'],clue:'A fossil collected by Anning and recorded in a museum.',supports:'the physical shape of a once-living animal',limit:'Anning’s exact thoughts when she found it',change:'fossil discoveries helped ideas about ancient life develop',cause:'careful collecting gave scientists more evidence to study',word:['fossil','preserved remains or traces of ancient life'],source:'https://www.nhm.ac.uk/discover/mary-anning-unsung-hero.html' },
  { year:2,title:'The first Moon landing',context:'Apollo 11 landed people on the Moon in July 1969. Neil Armstrong and Buzz Aldrin explored the surface while Michael Collins remained in lunar orbit. Many engineers, scientists and other workers helped make the mission possible.',sequence:['Apollo 11 launching from Earth','the Moon landing','the crew returning to Earth'],clue:'NASA photographs and mission records from Apollo 11.',supports:'recorded stages and activities of the mission',limit:'every worker’s personal feelings',change:'people could study Moon samples brought back to Earth',cause:'teamwork and earlier missions helped prepare Apollo 11',word:['mission','a planned task with a goal'],source:'https://www.nasa.gov/mission/apollo-11/' },
  { year:2,title:'School life across generations',context:'School objects and memories help us compare learning across generations. Some older classrooms used slates or ink pens; today many use pencils and computers. Experiences varied by place and family, so one picture cannot represent every school.',sequence:['a school photograph dated long ago','a later photograph of that school','the school today'],clue:'A dated class photograph showing desks and writing tools.',supports:'objects visible in that classroom',limit:'how every school in the country was arranged',change:'some classroom tools changed while learning to read continued',cause:'new tools and changes in education affected classrooms',word:['generation','people born around a similar time'],source:NA+'curriculum-topics/?curriculum-topic=victorians' },
  { year:2,title:'Remembering a local person',context:'Places sometimes remember a person with a plaque, building name or statue. A memorial tells us someone chose to remember them, but it is not their whole life story. We can use dated records to investigate the person and ask who else helped.',sequence:['a local person’s life','a memorial made after an event','people studying the memorial today'],clue:'A dated plaque naming a person and an achievement.',supports:'who the plaque’s makers chose to commemorate',limit:'a complete account of the person’s life',change:'communities can change how they remember a person',cause:'an achievement or local connection can lead to a memorial',word:['commemorate','remember someone or something publicly'],source:'https://historicengland.org.uk/education/schools-resources/' },
  { year:3,title:'Hunter-gatherers in Britain',context:'For much of prehistory people obtained food by gathering plants and hunting animals. Their ways of life changed with climate and landscape. Stone tools and other remains survive, but no written diary tells us the thoughts of these early people.',sequence:['hunter-gatherer life before farming','farming arriving in Britain about 4000 BCE','later metalworking'],clue:'A carefully shaped prehistoric stone tool.',supports:'a skill used to make a cutting edge',limit:'the maker’s name or exact beliefs',change:'farming later changed how many people obtained food',cause:'people shared new farming skills and brought crops and animals',word:['prehistory','the time before written records for a place'],source:EH+'prehistory/' },
  { year:3,title:'The first farmers',context:'Farming reached Britain around 4000 BCE. People grew crops and kept animals, while some gathering and hunting continued. Farming changed landscapes and work; it was a gradual process rather than a switch pressed everywhere on the same day.',sequence:['life before farming in Britain','early farming around 4000 BCE','later Bronze Age communities'],clue:'Charred ancient cereal grains found at an excavated site.',supports:'that cereal plants were present at that site',limit:'exactly how every family divided farming work',change:'crop growing and animal keeping became important',cause:'farming knowledge and domesticated plants and animals reached Britain',word:['domesticated','adapted over generations for living with people'],source:EH+'prehistory/' },
  { year:3,title:'Stonehenge and shared effort',context:'Stonehenge developed in stages over many centuries. Its builders moved and arranged large stones without modern cranes. Archaeology helps reconstruct parts of this work, but the monument’s complete meaning to every person who used it is uncertain.',sequence:['early earthworks at Stonehenge','later large stone settings','archaeologists studying the monument'],clue:'The surviving stones and excavated building remains.',supports:'some stages of construction and the monument’s layout',limit:'one certain explanation of every ceremony held there',change:'the monument’s form changed through repeated building',cause:'organised labour and shared plans made large construction possible',word:['monument','a structure made with special importance'],source:EH+'prehistory/' },
  { year:3,title:'Bronze Age makers and traders',context:'Bronze is made mainly from copper and tin. Bronze Age makers cast tools and ornaments, and materials travelled through networks of exchange. Stone tools did not vanish immediately; people often used older and newer materials alongside one another.',sequence:['Stone Age communities','Bronze Age metalworking','Iron Age communities'],clue:'A bronze axe found with a recorded archaeological location.',supports:'metalworking skill and the axe’s physical design',limit:'the complete journey of its metal without further evidence',change:'metalworking added new tools and forms of decoration',cause:'sharing materials and skills supported bronze production',word:['exchange','giving something and receiving something in return'],source:EH+'prehistory/' },
  { year:3,title:'Iron Age communities',context:'Iron Age Britain contained many communities rather than one united modern country. People farmed, traded and made iron tools. Hillforts and roundhouses are archaeological clues, but not everyone lived in a hillfort and its use could change over time.',sequence:['Bronze Age Britain','Iron Age Britain','Roman invasion in 43 CE'],clue:'The banks and ditches of a surviving hillfort.',supports:'the scale and shape of its earthworks',limit:'that every person used it in exactly the same way',change:'ironworking became important alongside farming and trade',cause:'new metalworking skills supported different tools',word:['hillfort','an enclosed hilltop site with defensive earthworks'],source:EH+'prehistory/' },
  { year:3,title:'Ancient Egypt and the Nile',context:'Ancient Egyptian civilisation developed around the Nile. Farming, transport and settlement relied on this river, and rulers organised large building projects. Objects and writing preserve evidence, but grand royal tombs do not describe every ordinary person’s life.',sequence:['early communities beside the Nile','the age of the pyramid builders','later Egyptian kingdoms'],clue:'An ancient Egyptian image showing agricultural work.',supports:'how its maker represented farming',limit:'that all farm workers had identical lives',change:'Egyptian settlements and government developed over many centuries',cause:'the Nile supported farming and movement of goods',word:['civilisation','a society with complex settlements and organisation'],source:BM+'ancient-egypt' },
  { year:4,title:'Earliest civilisations: a world overview',context:'Early complex societies developed in several places, including Sumer, Egypt, the Indus Valley and Shang China. They were not steps on one ladder, and their periods overlapped. Maps and timelines help us compare regions without pretending they were identical.',sequence:['early settlements before large cities','cities developing in several river valleys','archaeologists studying their remains'],clue:'A map showing the locations of early civilisation sites.',supports:'where mapped settlements were located',limit:'that all societies followed exactly the same path',change:'some settlements grew into cities with specialised work',cause:'food production and exchange supported larger settlements',word:['specialised','focused on a particular kind of work'],source:HISTORY_CURRICULUM_SOURCE },
  { year:4,title:'Egyptian writing and everyday work',context:'Egyptian scribes used writing to keep records as well as to tell religious stories. Not everyone could read and write, and many worked as farmers or craftspeople. Surviving objects allow us to study ordinary activities alongside the lives of rulers.',sequence:['an Egyptian object being made','its use in ancient life','its discovery and study in a museum'],clue:'An Egyptian record listing goods.',supports:'what goods that record describes',limit:'the opinions of every person who supplied those goods',change:'records helped organise increasingly complex activities',cause:'governments and workers needed ways to keep track of goods',word:['scribe','a person whose work included writing records'],source:BM+'ancient-egypt/life-ancient-egypt' },
  { year:4,title:'Rome arrives in Britain',context:'Emperor Claudius launched a Roman invasion of Britain in 43 CE. Conquest took time and did not include all of today’s Britain. Local rulers and communities responded in different ways: some resisted, while others made agreements with Roman power.',sequence:['Iron Age Britain before 43 CE','the Roman invasion in 43 CE','Roman rule developing in conquered areas'],clue:'Roman forts and objects found at excavated sites.',supports:'Roman military presence at particular places',limit:'that every local person welcomed Roman rule',change:'Roman rule introduced new institutions in conquered areas',cause:'Roman leaders sought territory, resources and political prestige',word:['conquest','taking control of an area by force'],source:EH+'romans/' },
  { year:4,title:'Boudicca and resistance',context:'Around 60–61 CE Boudicca led a revolt against Roman rule. Roman writers describe the events, but wrote from their own positions and did not preserve Boudicca’s own account. Archaeological destruction layers help historians investigate the conflict alongside written evidence.',sequence:['the Roman invasion in 43 CE','Boudicca’s revolt around 60–61 CE','continued Roman rule after the revolt'],clue:'Burnt archaeological layers in towns attacked during the revolt.',supports:'that destructive burning occurred at those sites',limit:'Boudicca’s exact words before the battle',change:'the revolt challenged Roman control but did not end it',cause:'abuses of Roman power helped provoke resistance',word:['resistance','opposition to control or an action'],source:EH+'romans/' },
  { year:4,title:'Roman towns, roads and baths',context:'Roman towns brought streets, public buildings and bathhouses to parts of Britain. Roads connected settlements and supported military and commercial journeys. Wealth and access differed: a large villa cannot stand for the home of every person in Roman Britain.',sequence:['Roman conquest beginning','towns and roads developing under Roman rule','archaeologists uncovering surviving structures'],clue:'An excavated bathhouse with rooms and heating remains.',supports:'how that bathhouse was arranged and heated',limit:'that every person could use every bathhouse',change:'roads and towns changed some landscapes and journeys',cause:'armies, trade and government needed reliable connections',word:['infrastructure','structures and networks that support everyday activity'],source:EH+'romans/' },
  { year:4,title:'Hadrian’s Wall and a connected empire',context:'Building on Hadrian’s Wall began in 122 CE. Forts, gates and settlements formed a frontier system, with people arriving from different parts of the Roman world. A frontier was a place of control and movement, not simply a line stopping every crossing.',sequence:['the invasion in 43 CE','wall building beginning in 122 CE','the end of rule from Rome in the early 400s'],clue:'Inscriptions naming units serving on the Roman frontier.',supports:'some recorded military units and their connections',limit:'the life story of every person near the wall',change:'frontier buildings changed as Roman priorities changed',cause:'Roman government wanted to manage its northern frontier',word:['frontier','a boundary area of a state or empire'],source:EH+'romans/' },
  { year:5,title:'After Roman rule: Britons and Scots',context:'Rule from Rome ended in Britain in the early fifth century, but people already living there remained. Communities in Britain and Ireland had varied languages, beliefs and rulers. Migration and contact helped shape kingdoms, including the Gaelic kingdom of Dál Riata.',sequence:['Roman rule in Britain','the ending of rule from Rome','early medieval kingdoms developing'],clue:'Settlements and objects dated after the end of Roman rule.',supports:'that people continued to live and work in Britain',limit:'that everyone suddenly shared a single new identity',change:'political rule changed while communities continued',cause:'Roman authority weakened and local rulers gained importance',word:['migration','people moving to live in another place'],source:EH+'early-medieval/' },
  { year:5,title:'Anglo-Saxon settlement and belief',context:'Angles, Saxons and other groups migrated to Britain from continental Europe. Several kingdoms developed rather than one instant England. Religious beliefs also changed; Christian missions and existing Christian communities contributed to a gradual process of conversion.',sequence:['migration after Roman rule','several Anglo-Saxon kingdoms developing','Christianity spreading among those kingdoms'],clue:'An early medieval burial containing jewellery and other objects.',supports:'some objects chosen for that burial',limit:'the precise beliefs of everyone in the kingdom',change:'religious practices changed gradually in different communities',cause:'missionaries, rulers and contacts helped spread Christianity',word:['conversion','a change in religious belief'],source:EH+'early-medieval/introduction/' },
  { year:5,title:'Vikings: raiders, traders and settlers',context:'People from Scandinavia travelled widely during the Viking Age. Some raided; others traded, farmed or settled, and individuals could do several of these things. Describing all Scandinavians as raiders hides the varied work and lives of these communities.',sequence:['the raid on Lindisfarne in 793 CE','larger Viking armies and settlement in the 800s','later Scandinavian influence in England'],clue:'Place names ending in “by” in parts of England.',supports:'evidence of Scandinavian language in place naming',limit:'the complete history of every resident of that place',change:'settlement added language and cultural influences',cause:'opportunities for trade, land and power encouraged travel',word:['settlement','a place where people make their homes'],source:EH+'early-medieval/' },
  { year:5,title:'Alfred, kingdoms and later rulers',context:'Alfred of Wessex defeated a Viking army at Edington in 878. Agreements and later campaigns changed control of territory, but rulers did not create today’s England in a single day. Later, the Danish king Cnut ruled England as part of a wider realm.',sequence:['Alfred’s victory at Edington in 878','Æthelstan ruling in the 900s','Cnut ruling England from 1016'],clue:'Coins carrying the name of a ruler.',supports:'a ruler’s claim to authority where coins circulated',limit:'that all people approved of that ruler',change:'territorial control and royal authority changed over time',cause:'warfare, agreements and succession altered who ruled',word:['succession','the process by which a new ruler takes over'],source:EH+'early-medieval/introduction/' },
  { year:5,title:'Ancient Greek city-states',context:'Ancient Greece contained many city-states, including Athens and Sparta. They had distinct ways of governing and sometimes fought each other. Shared languages, festivals and beliefs connected communities, but these connections did not make one united modern nation.',sequence:['Greek city-states developing','classical Athens in the fifth century BCE','later Hellenistic kingdoms'],clue:'Greek coins with symbols linked to different city-states.',supports:'images used by those issuing communities',limit:'that every Greek city-state had identical laws',change:'forms of government differed and changed over time',cause:'local histories and struggles for power shaped governments',word:['city-state','a city and surrounding land with its own government'],source:BM+'ancient-greece' },
  { year:5,title:'Athens: participation and exclusion',context:'Classical Athens allowed eligible male citizens to take part in democracy. Women, enslaved people and resident foreigners were excluded from this political participation. Comparing Athens with later democracies means studying both its influence and the limits of who could take part.',sequence:['Athens before its democratic reforms','democratic participation in classical Athens','later societies debating democratic ideas'],clue:'An ancient Athenian object connected with voting.',supports:'one method used in civic decision making',limit:'that every Athenian had the right to vote',change:'eligible citizens gained forms of direct participation',cause:'political reforms altered who could share in decisions',word:['citizen','a member of a political community with defined rights'],source:BM+'ancient-greece' },
  { year:6,title:'Greek ideas, art and their legacy',context:'Greek thinkers, artists and writers contributed ideas that later societies adapted. Pots can show sport, work or mythology, but a mythical scene is not a photograph of a real event. A legacy changes as later people select and reinterpret parts of the past.',sequence:['an ancient Greek object being made','later people studying Greek ideas','modern adaptations of those ideas'],clue:'An ancient Greek pot painted with a sporting scene.',supports:'how its painter represented a sporting activity',limit:'that every pictured event happened exactly as shown',change:'later cultures adapted Greek art and ideas',cause:'preserved texts and objects allowed ideas to travel across time',word:['legacy','an influence passed from the past to later people'],source:BM+'ancient-greece/visit-resource-greek-everyday-life' },
  { year:6,title:'The Kingdom of Benin',context:'Our main study is Benin in West Africa, c.AD 900–1300, in what is now southern Nigeria. Edo oral traditions describe earlier Ogiso rulers and a change to the oba dynasty around 1200; exact early dates are uncertain. Britain also had changing kingdoms: Norman rule followed the conquest of England in 1066. Compare these different histories during overlapping centuries, not as identical systems or steps on one ladder. Benin’s early court supported craft traditions. Many surviving brass plaques are from later centuries and cannot alone show life in c.AD 900–1300. The historic kingdom is distinct from the modern Republic of Benin.',sequence:['the earlier Ogiso rulers remembered in Edo oral traditions','the change to the oba dynasty traditionally placed around 1200','the developing kingdom by around 1300'],clue:'A recorded Edo oral tradition about earlier rulers and the beginning of the oba dynasty.',supports:'how changes in early royal leadership were remembered',limit:'every early ruler’s exact dates or every household’s daily life',change:'royal leadership changed from the remembered Ogiso rulers to the oba dynasty',cause:'changes in leadership and links with neighbouring Ife shaped traditions of rule',word:['oba','the title of the ruler of the Kingdom of Benin'],source:'https://www.nms.ac.uk/discover-catalogue/the-court-arts-and-history-of-the-kingdom-of-benin' },
  { year:6,title:'Benin art: evidence and ownership',context:'This later extension follows our main Benin study of c.AD 900–1300. Many surviving brass plaques were made from the 1500s onwards; do not treat them as direct pictures of the earlier period. Benin artworks provide evidence of craftsmanship and royal history. British forces attacked Benin City in 1897 and took many objects, which entered collections abroad. Studying an object includes asking how it reached a museum and whose perspectives its label includes.',sequence:['an artwork made in Benin in a later century','objects taken during the British attack in 1897','later debates about return and museum display'],clue:'A museum’s acquisition record for a Benin artwork.',supports:'a recorded part of the object’s journey into a collection',limit:'that taking the object was fair or freely agreed',change:'many objects were moved from Benin to collections abroad',cause:'the 1897 British attack led to large-scale taking of artworks',word:['provenance','the recorded history of an object’s ownership and movement'],source:'https://www.britishmuseum.org/about-us/british-museum-story/contested-objects-collection/benin-bronzes' },
  { year:6,title:'Local buildings across centuries',context:'A local-history enquiry can connect national changes with a particular place. A building may have been extended, renamed or used differently. Compare dated maps, photographs and records; do not invent a local story when the evidence has not been found.',sequence:['the earliest dated record chosen for a place','a later record of the same place','the place today'],clue:'Two dated maps and a photograph of the same building.',supports:'recorded changes in its surroundings and visible features',limit:'its exact first building date if no dated evidence survives',change:'a building’s use can change while part of its structure remains',cause:'changing community needs can lead to new uses of buildings',word:['archive','a collection of records preserved for study'],source:'https://historicengland.org.uk/education/schools-resources/' },
  { year:6,title:'Learning and childhood beyond 1066',context:'Access to education in Britain changed over centuries. Families’ wealth, location and laws affected children’s opportunities. Nineteenth-century reforms expanded schooling, but change took time; a law and everyday experience are different kinds of evidence.',sequence:['schooling before nineteenth-century reforms','laws expanding elementary education','schooling in later generations'],clue:'A historical school attendance register.',supports:'the attendance recorded for named pupils',limit:'whether every recorded pupil enjoyed each lesson',change:'access to elementary education widened over time',cause:'campaigning and legislation helped expand schooling',word:['legislation','laws made through a formal process'],source:NA+'curriculum-topics/?curriculum-topic=victorians' },
  { year:6,title:'Health and hospitals through time',context:'Healthcare has changed through new knowledge, public action and different systems of payment. Nightingale’s hospital reform and the creation of the NHS in 1948 are distinct developments. Progress was uneven: new systems did not instantly solve every illness or inequality.',sequence:['nineteenth-century hospital reforms','the NHS beginning in 1948','healthcare in later decades'],clue:'A hospital report from before or after a reform.',supports:'the conditions and measurements recorded in that report',limit:'the experience of every patient across Britain',change:'healthcare organisation and access changed over time',cause:'evidence, campaigning and political decisions supported reforms',word:['reform','a change intended to improve a system'],source:SM },
  { year:7,title:'1066 and rival claims',context:'Edward the Confessor died in 1066 without a surviving child. Rival claims to England’s throne led to invasions and battles. Harold defeated an invading army at Stamford Bridge before William’s army defeated Harold’s at Hastings; victory and a convincing claim are different questions.',sequence:['Edward’s death in January 1066','the Battle of Stamford Bridge in September','the Battle of Hastings in October'],clue:'The Bayeux Tapestry’s embroidered account of the conquest.',supports:'how its makers presented parts of the conquest',limit:'an impartial record of everything every claimant said',change:'William became king after the Norman victory',cause:'rival claims and military success altered the succession',word:['claimant','a person who says they have a right to something'],source:EH+'early-medieval/introduction/' },
  { year:7,title:'Norman control and castles',context:'Norman rulers used castles, landholding and officials to strengthen control after 1066. Castles were military strongpoints and statements of authority, but local populations could resist. Studying conquest includes its effects on people whose land or security was threatened.',sequence:['Anglo-Saxon rule before 1066','Norman conquest and early castles','later rebuilding of some castles in stone'],clue:'Earthworks and masonry from a castle’s building phases.',supports:'how the site’s buildings developed',limit:'that every local person accepted Norman authority',change:'new rulers and castles altered control of land',cause:'Norman rulers wanted to secure their authority',word:['authority','power recognised or exercised over others'],source:EH+'medieval/' },
  { year:7,title:'Domesday and medieval land',context:'The Domesday survey of 1086 recorded land, resources and obligations across much of England. Its records helped royal government understand wealth and rights. It did not list every person equally and was produced for governing purposes, not as an impartial family album.',sequence:['the Norman conquest in 1066','the Domesday survey in 1086','later historians examining the survey'],clue:'An entry in Domesday Book recording land and resources.',supports:'what the survey recorded for that holding',limit:'the feelings of all people who worked that land',change:'royal government gained a major written survey',cause:'the crown needed information about land and resources',word:['survey','a systematic collection of information'],source:NA+'students/videos/spotlight-on/spotlight-on-domesday-book/' },
  { year:7,title:'Magna Carta and royal power',context:'In 1215 King John agreed to Magna Carta after conflict with leading barons. It addressed particular medieval grievances, not equal voting rights for everyone. Its later reissues and reinterpretations helped some principles acquire meanings beyond the original political dispute.',sequence:['conflict between John and barons','Magna Carta agreed in 1215','later reissues and interpretations'],clue:'A surviving text of Magna Carta.',supports:'the terms written in that version of the charter',limit:'that all people immediately gained equal political rights',change:'written limits on some royal actions became politically important',cause:'conflict over rule and obligations led to the charter',word:['charter','a formal written grant or statement of rights'],source:NA+'teaching-resources/magna-carta-1214-1225/' },
  { year:7,title:'The Black Death and its effects',context:'Plague reached England in 1348 and caused devastating loss of life. People did not understand disease as modern scientists do. Population loss affected labour and wages, but experiences varied, and the consequences developed over years rather than at one instant.',sequence:['England before the plague arrived','plague arriving in 1348','changes in work and wages after population loss'],clue:'Manor records noting deaths and labour obligations.',supports:'changes recorded in that particular manor',limit:'an exact national death total from one manor',change:'loss of workers affected bargaining over work and wages',cause:'severe population loss reduced the available labour force',word:['consequence','a result of an event or action'],source:'https://www.nationalarchives.gov.uk/explore-the-collection/explore-by-time-period/early-modern/plague/' },
  { year:7,title:'Medieval protest and local lives',context:'The uprising of 1381 involved taxation, labour restrictions and demands about power. Participants were not all the same, and chronicles often came from educated people outside the protest. Local records and archaeology can widen a history that otherwise centres only on kings.',sequence:['labour changes after the Black Death','the uprising in 1381','later records and interpretations of the uprising'],clue:'A medieval chronicler’s account of the uprising.',supports:'the events and judgements that writer recorded',limit:'the views of every person who took part',change:'protest made grievances visible even when demands were rejected',cause:'taxation and restrictions on labour contributed to anger',word:['grievance','a complaint about unfair treatment'],source:EH+'medieval/' },
  { year:8,title:'Tudor religious change',context:'Henry VIII’s break with Rome changed the organisation of the English Church. Edward VI, Mary I and Elizabeth I pursued different religious policies. These were political and religious changes with varied local responses; they did not instantly make everybody believe the same thing.',sequence:['Henry VIII’s break with Rome in the 1530s','religious changes under Edward VI and Mary I','Elizabeth I’s settlement from 1559'],clue:'A government order about worship in a Tudor parish.',supports:'what officials wanted the parish to do',limit:'what every worshipper privately believed',change:'church organisation and required worship changed repeatedly',cause:'royal politics and religious ideas both drove change',word:['Reformation','changes to Christian churches in sixteenth-century Europe'],source:NA+'resources/the-english-reformation-c1527-1590/' },
  { year:8,title:'Elizabethan images and interpretations',context:'Elizabeth I ruled from 1558 to 1603. Royal portraits used clothing, symbols and setting to communicate authority. Historians compare these crafted images with records of decisions and events; a ruler’s public image is evidence of representation, not proof of universal popularity.',sequence:['Elizabeth becoming queen in 1558','portraits and policies during her reign','her death in 1603 and later interpretations'],clue:'A formal portrait of Elizabeth I with symbolic objects.',supports:'an intended public image of royal authority',limit:'the queen’s appearance and feelings in every ordinary moment',change:'public images helped shape how monarchy was represented',cause:'rulers and patrons wanted to communicate status and legitimacy',word:['interpretation','an explanation or understanding of evidence'],source:NA+'curriculum-topics/?curriculum-topic=renaissance-and-reformation' },
  { year:8,title:'Civil wars and competing authority',context:'Conflicts over religion, money and government contributed to civil wars across England, Scotland and Ireland. Fighting began in England in 1642; Charles I was executed in 1649. Different communities experienced the conflicts differently, and neither royal nor parliamentary supporters were one uniform group.',sequence:['growing disputes before 1642','civil war beginning in England in 1642','Charles I’s execution in 1649'],clue:'A pamphlet printed by supporters of one side.',supports:'arguments its makers wanted readers to accept',limit:'an impartial account of both sides’ actions',change:'the monarchy was abolished for a period after 1649',cause:'disputes about power, finance and religion helped cause conflict',word:['civil war','war between groups within a country'],source:NA+'resources/civil-war/' },
  { year:8,title:'Restoration, revolution and Parliament',context:'The monarchy returned under Charles II in 1660. James II later lost power during the events of 1688–89, and William and Mary became monarchs. These changes strengthened parliamentary constraints, while voting remained restricted and conflict continued elsewhere in the kingdoms.',sequence:['the Restoration in 1660','the events of 1688–89','the Bill of Rights in 1689'],clue:'The written terms of the Bill of Rights.',supports:'formal restrictions and principles set out in the document',limit:'that everyone gained an equal vote in 1689',change:'constraints on royal government became more firmly stated',cause:'conflicts over religion and royal power prompted political change',word:['constitutional','relating to the rules and organisation of government'],source:NA+'resources/glorious-revolution/' },
  { year:8,title:'Industry: energy, work and towns',context:'Industrialisation changed production, transport and settlement unevenly. Coal, steam power, investment and workers all mattered; one invention did not cause the whole process. Factory and town records allow us to investigate both opportunities and dangerous working or living conditions.',sequence:['production before widespread steam-powered factories','industrial expansion in the eighteenth and nineteenth centuries','later reforms of work and public health'],clue:'A factory inspector’s report describing working conditions.',supports:'conditions recorded in the inspected factory',limit:'the experience of every worker in every industry',change:'factory production and industrial towns expanded',cause:'energy, technology, capital and labour supported industrial growth',word:['industrialisation','the growth of machine-based industry'],source:NA+'curriculum-topics/?curriculum-topic=victorians' },
  { year:8,title:'Enslavement, resistance and abolition',context:'Enslavement denied people freedom and treated them as property. Britain profited from the Atlantic slave trade; enslaved people resisted, and Black and white abolitionists campaigned against it. The 1807 law banned Britain’s slave trade, while the 1833 law addressed slavery in most British colonies; freedom was not immediate everywhere.',sequence:['resistance and abolition campaigning','the British slave-trade ban in 1807','the slavery abolition law of 1833'],clue:'A petition or testimony used in the abolition campaign.',supports:'the argument and experience its author presented',limit:'the experiences of every enslaved person',change:'laws challenged trade and legal enslavement, with continuing limits',cause:'resistance and sustained campaigning helped bring legal change',word:['abolition','ending an institution or practice by law'],source:NA+'resources/slavery/' },
  { year:9,title:'Rights, reform and women’s votes',context:'Political rights in Britain expanded through long campaigns and laws. In 1918 some women over 30 gained parliamentary voting rights, subject to qualifications. In 1928 women gained the vote on the same age terms as men; neither change makes earlier campaigns irrelevant.',sequence:['campaigns before 1918','partial women’s enfranchisement in 1918','equal voting age terms in 1928'],clue:'A dated campaign petition asking for women’s voting rights.',supports:'the demand made by that petition’s supporters',limit:'that every woman supported identical campaign methods',change:'more women gained the legal right to vote',cause:'sustained campaigning and political decisions helped expand rights',word:['suffrage','the right to vote in political elections'],source:'https://www.parliament.uk/about/living-heritage/transformingsociety/electionsvoting/womenvote/' },
  { year:9,title:'The First World War: causes and experience',context:'The First World War began in 1914 after a crisis involving European powers. Alliances, military planning, imperial rivalries and political choices contributed to its spread. People from many regions served or supported armies; their experiences cannot be reduced to a single soldier’s account.',sequence:['international tensions before 1914','war beginning in 1914','the armistice on 11 November 1918'],clue:'A soldier’s dated letter written during the war.',supports:'what that writer chose to describe at that time',limit:'the experience of every person involved in the war',change:'the war altered societies, borders and many lives',cause:'several political and military factors turned a crisis into wider war',word:['armistice','an agreement to stop fighting'],source:'https://www.iwm.org.uk/sites/default/files/files/2023-10/first_world_war_large_print_guide.pdf' },
  { year:9,title:'The Second World War and civilian life',context:'Germany invaded Poland in September 1939; Britain and France then declared war on Germany. The conflict became global and affected civilians as well as armed forces. Evacuation, bombing and rationing changed life in Britain, but family experiences varied widely.',sequence:['Germany invading Poland in September 1939','wartime evacuation and rationing','the war ending in 1945'],clue:'A wartime ration book issued to a civilian.',supports:'the system used to allocate some limited supplies',limit:'exactly what its owner ate at every meal',change:'wartime restrictions altered shopping and family routines',cause:'war disrupted supplies and government allocated scarce goods',word:['rationing','limiting and sharing supplies through allowances'],source:'https://www.iwm.org.uk/sites/default/files/files/2021-01/Health%20and%20Wellbeing%20-%20Food%20and%20Nutrition-%20Teacher%20Notes.pdf' },
  { year:9,title:'The Holocaust: people, persecution and remembrance',context:'This sensitive topic is for older learners with a trusted grown-up; pause at any time. The Holocaust was the systematic persecution and murder of six million European Jews by Nazi Germany and its allies and collaborators. Other groups were also persecuted and murdered. Jewish people had diverse lives before, during and after this history; they were never only victims.',sequence:['Jewish communities and lives before Nazi rule','Nazi persecution and the Holocaust during 1933–45','survivors rebuilding lives and later remembrance'],clue:'A survivor’s recorded testimony describing their own life.',supports:'that individual’s remembered experience and perspective',limit:'a complete account of every victim and survivor',change:'Nazi policies destroyed lives and communities through persecution and genocide',cause:'antisemitism and choices by Nazi authorities and collaborators drove persecution',word:['antisemitism','prejudice, hostility or discrimination against Jewish people'],source:'https://encyclopedia.ushmm.org/content/en/article/introduction-to-the-holocaust' },
  { year:9,title:'Empire, independence and migration',context:'Britain’s empire involved conquest, unequal power, trade, resistance and varied local experiences. Many colonies became independent during the twentieth century. Migration also connected Britain with other places; Caribbean arrivals on Empire Windrush in 1948 were part of a much longer history, not its beginning.',sequence:['British imperial rule in many regions','India and Pakistan gaining independence in 1947','Empire Windrush arriving in Britain in 1948'],clue:'An oral-history interview with a migrant about their journey.',supports:'the speaker’s remembered experiences and reasons',limit:'the reasons and experiences of every migrant',change:'independence changed political rule while connections continued',cause:'anti-colonial movements and changing political conditions supported independence',word:['independence','self-government rather than rule by another state'],source:NA+'resources/archives-live-windrush-75/' },
  { year:9,title:'Post-war Britain: our local enquiry',context:'After 1945 Britain experienced changes in housing, healthcare, migration and work. Their timing and effects differed across places. A local enquiry compares maps, public records and consenting adults’ memories, then connects evidence to national developments without claiming every town followed one pattern.',sequence:['Britain at the end of the war in 1945','the NHS beginning in 1948','later changes investigated in a local place'],clue:'Dated local maps, public records and an adult’s volunteered memory.',supports:'different kinds of evidence about the chosen local place',limit:'a single certain national story from one neighbourhood',change:'local services, housing and communities changed unevenly',cause:'national policies and local decisions both shaped post-war change',word:['oral history','a recorded account of someone’s remembered experiences'],source:'https://historicengland.org.uk/education/schools-resources/' },
];

const LENSES = [
  { title:'Build the timeline', aim:'Put events in sequence and explain what came before and after', word:'chronology', meaning:'the order in which events happened' },
  { title:'Be an evidence detective', aim:'Use a source clue to make a careful claim and identify its limits', word:'evidence', meaning:'information used to support or question an explanation' },
  { title:'Spot change and continuity', aim:'Explain a change without assuming everything changed at once', word:'continuity', meaning:'something that remains similar through a period of change' },
  { title:'Connect causes and consequences', aim:'Explain how a reason contributed to change without confusing order with cause', word:'cause', meaning:'a reason that helps explain why something happened' },
  { title:'Listen to different perspectives', aim:'Distinguish an individual perspective from an account of everybody', word:'perspective', meaning:'a person’s position or way of seeing something' },
  { title:'Curate your history discovery', aim:'Construct an evidence-based explanation and name a question still unanswered', word:'enquiry', meaning:'an investigation guided by a question' },
] as const;

// The same six history skills, introduced with spoken-friendly words for KS1.
const YOUNG_LENSES = [
  { word:'order', meaning:'which thing happened first, next and last', wrong:['a reason why it happened','a clue about what someone saw'] },
  { word:'clue', meaning:'something that helps us learn about the past', wrong:['a guess about tomorrow','a story we know was made up'] },
  { word:'same', meaning:'something that stays similar over time', wrong:['something that changes','something we do not know yet'] },
  { word:'reason', meaning:'why something happened', wrong:['when it happened','where it happened'] },
  { word:'view', meaning:'what one person sees or thinks', wrong:['what everyone must think','what nobody could remember'] },
  { word:'question', meaning:'something we want to find out', wrong:['an answer we already know','a made-up story told as true'] },
] as const;

const YOUNG_DISCOVERIES: Record<string,string> = {
  'My own history':'History is about the past. You were once a baby. Later, you started school. Now you are learning new things. People can remember parts of their lives. You can talk about a made-up child if you do not want to share your own story.',
  'Toys then and now':'Children played long before computer games. Some toys were made from wood. Dolls and balls are old ideas that children still enjoy today. Some newer toys have motors or screens. An old toy cannot tell us its owner’s whole story.',
  'Homes and household objects':'People needed food, warmth and a place to sleep in the past too. Before electric lights, a candle could help light a room. Many homes later got electric lights. Homes were not all the same. Old objects can give us clues about daily life.',
  'Journeys in living memory':'People walk, cycle or ride to different places. A grown-up may remember how they went to school as a child. Their route may be different from yours. Their memory tells us about one person’s journey. Other people may remember different journeys.',
  'Sending messages':'People sent letters before there were telephones. Later, people could talk over a telephone. Computers brought new ways to send messages. We still use letters today. A new invention does not make every old way disappear.',
  'Our local history trail':'Look at a place near your home with a grown-up. Some buildings are older than others. An old map or a dated photo can give us clues. A building can look old without being very old. We need clues before we decide.',
  'The Great Fire of London':'A large fire began in London in September 1666. It started in a bakery in Pudding Lane. Buildings stood close together. Wind helped the fire spread. People escaped, and the city was rebuilt. Old maps and diaries help us find out what happened.',
  'Florence Nightingale and nursing':'Florence Nightingale helped care for people during the Crimean War. She worked with other nurses. Later, she asked for better hospitals. She used numbers to show problems. Many people helped improve care. One person did not do everything alone.',
  'Mary Anning’s fossil clues':'Mary Anning looked for fossils near Lyme Regis long ago. Fossils are remains or traces of ancient living things. Her finds helped people learn about animals from the distant past. She worked carefully. Her story also helps us ask whose work people remember.',
  'The first Moon landing':'Apollo 11 took three astronauts towards the Moon in July 1969. Neil Armstrong and Buzz Aldrin walked on the Moon. Michael Collins stayed in a spacecraft going around it. Many people on Earth helped. The astronauts later came back to Earth.',
  'School life across generations':'Children learned at school before computers were invented. Some older classrooms used slates or ink pens. Many classrooms now have pencils and computers. Children still learn to read. One old class photo shows one school, not every school.',
  'Remembering a local person':'A place may remember someone with a sign, a statue or a building name. A sign can tell us who people chose to remember. It cannot tell us their whole life story. A grown-up can help you look for another clue. Other people may have helped too.',
};
const YOUNG_AIMS = [
  'Put the story in order. Say what came first, next and last.',
  'Use a clue to say what we know. Think of something else to find out.',
  'Spot one thing that changed. Look for something that stayed the same.',
  'Find a reason for a change. Tell someone why it happened.',
  'Ask who made or remembered a clue. Listen to another person’s story.',
  'Make a little museum label. Tell a visitor what your clue can show.',
] as const;
function imaginedClue(t:Topic):string {
  return `Imagine finding this clue: ${t.clue.charAt(0).toLowerCase()+t.clue.slice(1)}`;
}
function teachingClue(t:Topic):string {
  return t.year <= 2
    ? `${imaginedClue(t)} What could it tell us? It could help us find out ${t.supports}. It could not tell us ${t.limit}. We would need another clue. Tell a grown-up one thing you could learn and one question you would ask.`
    : `${imaginedClue(t)} It could support an explanation about ${t.supports}, but not establish ${t.limit}. Ask who made it, when it was made and why. Compare it with another relevant source before drawing a wider conclusion. A useful clue can leave important questions unanswered.`;
}
function workedExample(t:Topic):CourseLesson['example'] {
  return t.year <= 2
    ? {prompt:`${imaginedClue(t)} What could we learn?`,explanation:`First, think about what the clue could show: ${t.supports}. Now ask what it cannot tell us: ${t.limit}. That is a question for another clue. Say one thing you could learn, then draw or say your next question.`}
    : {prompt:`${imaginedClue(t)} What could it show, and what would remain uncertain?`,explanation:`Start with the source and its context. A careful claim concerns ${t.supports}. Then state a limit: this clue alone cannot establish ${t.limit}. Seek another relevant source to test or extend the explanation. Distinguishing a supported claim from an open question makes your historical argument stronger.`};
}

function question(prompt: string, right: string, alternatives: [string, string], hint: string, explanation: string, seed: number): CourseQuestion {
  const options = [right, ...alternatives];
  const answer = seed % options.length;
  for (let n = 0; n < answer; n += 1) options.unshift(options.pop()!);
  return { prompt, options, answer, hint, explanation };
}

function focusQuestions(t: Topic, focus: number, seed: number): CourseQuestion[] {
  if (t.year <= 2) return youngFocusQuestions(t,focus,seed);
  const q = (prompt:string, right:string, wrong:[string,string], hint:string, explanation:string, offset=0) => question(prompt,right,wrong,hint,explanation,seed+offset);
  const first = t.sequence[0], middle = t.sequence[1], last = t.sequence[2];
  const focused: CourseQuestion[][] = [
    [q(`In our ${t.title} timeline, what comes first?`,first,[middle,last],'Follow the order in the teaching story.',`The sequence begins with ${first}, followed by ${middle}, then ${last}.`),
      q(`Which event comes after ${middle}?`,last,[first,'All three happened at the same instant'],'Read the final step of the timeline.',`${last} is the last step. A sequence tells us order; it does not by itself tell us the reason for an event.`,1)],
    [q(`Clue: ${t.clue} Which claim can it support?`,t.supports,['every detail of everybody’s life','an exact account of events outside its date and place'],'Make the claim no wider than the evidence.',`This clue can support ${t.supports}. Its usefulness depends on the question we ask.`),
      q(`Can this clue alone prove ${t.limit}?`,'No: we need other evidence',['Yes: one clue always proves every detail','Yes: if our story sounds exciting'],'Ask what is actually present in the clue.',`The clue has limits. We should not turn an unanswered question into a fact.`,1)],
    [q(`Which change is supported in ${t.title}?`,t.change,['every person’s life changed in exactly the same way','everything from the earlier period disappeared'],'Look for the specific change described in the story.',`The supported change is that ${t.change}. This does not prove universal or instant change.`),
      q('What would help us investigate continuity across this period?','Compare evidence from before and after the change',['Study only the latest period and guess the earlier one','Assume everything stayed the same'],'Continuity is a comparison across time.',`For ${t.title}, compare the earlier step (${first}) with later evidence (${last}). Identify what stayed similar as well as what changed.`,1)],
    [q(`Which reason helps explain the change in ${t.title}?`,t.cause,['every change has exactly one cause','events happen only because dates become later'],'A cause is an explanation, not just a date.',`The teaching gives a reason: ${t.cause}. Other causes may also matter.`),
      q(`Does ${first} coming before ${middle} automatically prove it caused it?`,'No: order alone does not prove a cause',['Yes: every earlier event causes every later event','We must reverse the dates to find a cause'],'Before and because are different ideas.',`We need a connection supported by evidence. The order of these events is useful, but chronology alone cannot demonstrate causation.`,1)],
    [q(`What should a historian ask about the perspective behind this clue: ${t.clue}`,'Who made or recorded it, and for what purpose?',['Does it agree with me? If so, stop checking','Can I make it describe everyone without checking?'],'Think about the person or institution behind a record.',`Understanding a source’s maker and purpose helps us assess its perspective. It does not make the source useless.`),
      q(`What is a good response to a missing perspective in ${t.title}?`,'Look for another relevant record and state what remains unknown',['Invent a quotation from the missing person','Treat silence as proof everyone agreed'],'Missing evidence needs careful investigation.',`We can seek another perspective, but must not invent a historical voice. An absence of evidence does not automatically show agreement.`,1)],
    [q(`Which museum label is most careful for this clue: ${t.clue}`,`This clue helps us investigate ${t.supports}.`,['This clue proves every story about this period.','This clue tells us exactly what all people believed.'],'A museum label should match the evidence.',`The careful label states the supported claim and avoids pretending the object or record can answer every question.`),
      q(`Which question should our ${t.title} enquiry keep open?`,`What further evidence could tell us about ${t.limit}?`,['How can we hide any evidence that disagrees?','How can we replace records with an invented quotation?'],'Good enquiries welcome a question still unanswered.',`Naming a limit helps plan the next investigation. We could seek an appropriate second source rather than assert ${t.limit}.`,1)],
  ];
  return [
    ...focused[focus],
    q(`Which explanation of ${t.title} is supported by the lesson?`,`${t.change}; ${t.cause}.`,['Everyone had exactly the same experience throughout this period.','Nothing can be learned because the past is over.'],'Use the specific change and reason given in the teaching.',`We can explain that ${t.change}, and one contributing reason is that ${t.cause}. The evidence does not support a claim about identical experiences.`,2),
    q(`Why must we be careful with this evidence? ${t.clue}`,`It cannot alone establish ${t.limit}.`,['Every old source is automatically false.','Every old source contains every possible answer.'],'Useful evidence can still have limits.',`This source description is useful for ${t.supports}, but not enough to establish ${t.limit}.`,3),
    q(`In this enquiry, what does “${LENSES[focus].word}” mean?`,LENSES[focus].meaning,['a prediction about events that have not happened','an invented detail presented without supporting evidence'],'Use the focus vocabulary for this week.',`Here, ${LENSES[focus].word} means ${LENSES[focus].meaning}. Our topic word, ${t.word[0]}, means ${t.word[1]}.`,4),
  ];
}

function youngFocusQuestions(t:Topic, focus:number, seed:number): CourseQuestion[] {
  const q = (prompt:string, right:string, wrong:[string,string], hint:string, explanation:string, offset=0) => question(prompt,right,wrong,hint,explanation,seed+offset);
  const [first,middle,last]=t.sequence;
  const focused:CourseQuestion[][] = [
    [q(`Our ${t.title} story has three event cards. Which comes first?`,first,[middle,last],'Say the story with a grown-up. Point to the first card.',`Start with ${first}. Next comes ${middle}. Last comes ${last}.`),
      q(`Which card comes after ${middle}?`,last,[first,middle],'Point to the middle card. What comes next in our story?',`${last} comes after ${middle}. Follow the cards in the order shown in our story.`,1)],
    [q(`Our clue is: ${t.clue} What can we learn from it?`,t.supports,[t.limit,'what will happen tomorrow'],'Look at what the clue shows. It cannot tell us everything.',`This clue helps us learn about ${t.supports}. We need other clues to find out more.`),
      q('Can one clue tell us everything about the past?','No, we need other clues',['Yes, it tells us everything','Yes, a guess tells us the rest'],'A picture or an object can show some things, but not all things.','One clue can help, but it does not tell us everything. Look for another clue before deciding.',1)],
    [q(`Which change did our ${t.title} story describe?`,t.change,['everything stayed exactly the same','everyone changed in the same way'],'Look at the before and after parts of the story.',`Our story says ${t.change}. One change does not mean everything changed for everybody.`),
      q('Which pictures help us spot what changed?','A picture from before and one from after',['Two pictures from today','Two pictures from the same time'],'Look at the earlier picture, then the later picture.','Compare a before picture with an after picture. Look for what changed and what stayed similar.',1)],
    [q(`Why did a change happen in our ${t.title} story?`,t.cause,['only because time went by','because every change has just one reason'],'Listen for the reason in the story. A date is not a reason.',`One reason in our story is that ${t.cause}. There may be other reasons too.`),
      q('How can we check why a change happened?','Look for a reason and a clue',['Say the earlier event always made it happen','Look only at the date'],'Before tells us the order. A reason helps us say why.','A thing happening first does not always make the next thing happen. Find a reason and a clue.',1)],
    [q(`Our clue is: ${t.clue} How can we find out whose clue it is?`,'Ask who made or remembered it',['Say everyone felt the same','Invent the person who made it'],'A clue comes from an object, a record or a person.','Ask who made or remembered the clue. One person’s story does not tell us what everyone thought.'),
      q('If someone’s story is missing, what can we do?','Look for another clue',['Make up their story','Say everyone thought the same'],'We can ask another question. We do not need to invent a story.','Look for another clue and say what you still want to know. Do not make up someone’s words.',1)],
    [q(`We draw a label for this clue: ${t.clue} Which label is careful?`,`This clue helps us learn about ${t.supports}.`,['This clue tells us everything.','This clue speaks for everyone.'],'A label should tell us what we can find out from the clue.',`Keep the label close to the clue: it helps with ${t.supports}. Leave other questions open.`),
      q('What is a good question to ask next?','What else could we find out?',['How can we hide other clues?','What story can we make up?'],'A good question helps us look for another useful clue.','Ask what else you could find out. Another clue might answer a question that is still open.',1)],
  ];
  const lens=YOUNG_LENSES[focus];
  return [...focused[focus],
    q(`What changed in our story about ${t.title}?`,t.change,['everything stayed exactly the same','everyone changed in the same way'],'Look for the change named in the story.',`The story tells us ${t.change}. We should not say this happened to everyone in the same way.`,2),
    q(`Clue: ${t.clue} Does it tell us ${t.limit}?`,'No, we need another clue',['Yes, it shows everything','Yes, a guess is enough'],'A useful clue still leaves some things for us to find out.',`This clue helps with ${t.supports}. It does not tell us ${t.limit}, so we need another clue.`,3),
    q(`What does “${lens.word}” mean?`,lens.meaning,[...lens.wrong],`Use our history word: ${lens.word}. Say it with a grown-up.`,`Our word ${lens.word} means ${lens.meaning}. Use it when you draw or tell this history story.`,4),
  ];
}

function focusTeaching(t:Topic, focus:number): string {
  if (t.year <= 2) {
    return [
      `Let’s put the story in order. First: ${t.sequence[0]}. Next: ${t.sequence[1]}. Last: ${t.sequence[2]}. Draw three little pictures and point to each one. Say “before” and “after” as you move along. A picture can help you remember, but your drawing is your own work, not an old photograph.`,
      `A history detective looks for clues. Here is our clue description: ${t.clue} It can help us find out ${t.supports}. Look carefully before you guess. Can it also tell us ${t.limit}? No, we would need another clue. Say what you know, then say what you still want to find out.`,
      `Some things change and some stay similar. In this story, ${t.change}. Make two pictures: one for before and one for after. Point to the change. Did everything change for everybody at once? We cannot say that from one clue. Ask a grown-up to help you spot something that stayed similar, if the story tells us.`,
      `Why did something change? One reason is that ${t.cause}. A reason helps explain a change. Draw a reason picture and a change picture, then join them with an arrow. Tell a grown-up what the arrow means. Something happening first does not always mean it made the next thing happen.`,
      `Different people can remember different parts of a story. Our clue description is ${t.clue} Ask who made or remembered the clue. If we do not know, say “I have a question”. We should look for another clue instead of making up a person’s words. One person cannot tell us what everybody thought.`,
      `Let’s make a tiny paper museum! Draw your own picture of our clue and label it “my drawing”. Tell a visitor what it helps us find out: ${t.supports}. Now add a question about ${t.limit}. A careful museum label says what we know and what we still want to investigate.`,
    ][focus];
  }
  const texts = [
    `Our timeline begins with ${t.sequence[0]}. Next comes ${t.sequence[1]}, and finally ${t.sequence[2]}. Say or write these in order. Dates and words such as “before” and “after” help us keep the story clear; a timeline does not tell us everything about a period.`,
    `Inspect this evidence description: ${t.clue} Separate the thing we can observe from the claim we make about it. It supports ${t.supports}. An exciting story is not enough: each claim needs a relevant clue, and new evidence might change our explanation.`,
    `A supported change is that ${t.change}. Change can affect different people at different speeds, and older practices may continue alongside newer ones. Compare the earlier and later parts of this topic. If the evidence does not establish a continuity, write a question instead of inventing one.`,
    `One reason for change is that ${t.cause}. A cause helps explain an event; a consequence is something that follows from it. More than one cause may contribute. Draw an arrow only when you can explain the connection, rather than just because two events appear beside each other on a timeline.`,
    `A source or object gives a particular view of this topic. Ask who produced or preserved it, what it was for, and whose experience it does not show. A limited perspective can still be useful. Comparing relevant records helps us avoid making one voice stand for an entire community.`,
    `A careful museum explanation joins knowledge with evidence: ${t.change}. Our evidence description supports ${t.supports}, but it cannot alone establish ${t.limit}. Your exhibition should include both a supported claim and an honest question. Do not present your invented drawing or model as an original historical object.`,
  ];
  return texts[focus];
}

function mission(t:Topic, focus:number): CourseLesson['mission'] {
  const young = t.year <= 2;
  const response = young ? 'Draw or say your answer to a trusted grown-up.' : 'Write or draw your answer on paper; label claims and questions separately.';
  const activities = [
    ['Timeline trail', `Make three event cards: ${t.sequence.join('; ')}.`, 'Place the cards in order. Move or point along them while saying before, next and after.', 'Explain one gap in the timeline: what would you like to know between two steps?'],
    ['Evidence detective notebook', `Draw a simple symbol for this described clue: ${t.clue}`, `Make two boxes: “can support” (${t.supports}) and “does not establish” (${t.limit}).`, 'Add a question for a historian. Explain what kind of second clue might help answer it.'],
    ['Change tracker', `Make before and after panels for ${t.title}. Label them with two steps from the timeline.`, `Show this supported change: ${t.change}. Use arrows and words rather than assuming everything changed.`, 'Add a continuity you can support from the teaching, or mark continuity as an unanswered question.'],
    ['Cause-and-consequence chain', `Make a reason card saying: ${t.cause}. Make a change card saying: ${t.change}.`, 'Join them with an arrow. Tell someone why the connection makes sense using the lesson.', 'Add another card labelled “question”. What further evidence would help test this explanation?'],
    ['Whose viewpoint?', `Create an evidence card using this description: ${t.clue}`, 'Add three investigation questions: who made it, why, and whose voice is missing? Do not guess unknown answers as facts.', 'Design a second evidence card you would like to find. Label it “evidence to seek”, not a real discovered source.'],
    ['Mini museum curator', `Give your paper exhibit a title about ${t.title}. Draw a representation of the described clue, clearly labelled “my drawing”.`, `Write or say a careful label: “This can help us investigate ${t.supports}.”`, `Finish with an open question about ${t.limit}. Explain why your label avoids claiming to know everything.`],
  ][focus];
  return {title:activities[0],instructions:[response,'Spend about seven minutes exploring; there is no race or countdown.',...activities.slice(1),'Share one discovery. Keep family details private, use paper materials, and ask a grown-up before visiting a place or handling an old object.']};
}

export const HISTORY_LESSONS: CourseLesson[] = TOPICS.flatMap((t, topicIndex) => {
  const yearTopic = topicIndex % 6;
  return LENSES.map((lens, focus) => ({
    id:`history-y${t.year}-w${yearTopic*6+focus+1}-s1`,subject:'history' as const,year:t.year,week:yearTopic*6+focus+1,session:1,
    sensitive:t.title.includes('Holocaust') || undefined,
    title:`${t.title}: ${lens.title}`,unit:t.title,
    objective:t.year<=2 ? `${YOUNG_AIMS[focus]} Explore ${t.title}.` : `${lens.aim} in an enquiry about ${t.title}.`,
    teaching:[t.year<=2 ? YOUNG_DISCOVERIES[t.title] : t.context,focusTeaching(t,focus),teachingClue(t),
      t.year <= 2 ? `Draw or tell the story in your own words. Our history word is ${YOUNG_LENSES[focus].word}: ${YOUNG_LENSES[focus].meaning}. Ask for help reading when you need it. You can use a pretend child’s story. You do not have to share a family photo or a private memory.` : `Use the vocabulary carefully. ${t.word[0]} means ${t.word[1]}. Our focus is ${lens.word}: ${lens.meaning}. Support an explanation with a clue, and identify one limit. Historians compare sources and interpretations, then revise explanations when better evidence becomes available.`],
    vocabulary:[t.year<=2 && t.word[0]==='continuity'?{word:'change',meaning:'something becoming different'}:{word:t.word[0],meaning:t.word[1]},t.year<=2?{word:YOUNG_LENSES[focus].word,meaning:YOUNG_LENSES[focus].meaning}:{word:lens.word,meaning:lens.meaning},{word:'source',meaning:t.year<=2?'a picture, object or story that gives us a clue about the past':'an object, record or account used to investigate the past'}],
    example:workedExample(t),
    questions:focusQuestions(t,focus,topicIndex+focus),mission:mission(t,focus),
    reflection:t.year<=2 ? `Draw or tell one thing you learned about ${t.title}. Use our word “${YOUNG_LENSES[focus].word}” and one clue. What else would you like to find out?` : `Explain one thing you learned about ${t.title}. Use today’s skill (${lens.word}) and one clue. What question remains unanswered?`,source:t.source,
  }));
});
