import type { CartoonEpisodeManifest } from './episode-contract';

const archie = {
  id: 'archie',
  label: 'Archie',
  kind: 'character' as const,
  asset: '/assets/images/archie-character-v2.png',
  side: 'left' as const,
  entrance: 'walk' as const,
};

const bella = {
  id: 'bella',
  label: 'Bella',
  kind: 'character' as const,
  asset: '/assets/cartoon/friends/bella.png',
  side: 'right' as const,
  entrance: 'float' as const,
};

const sodaBot = {
  id: 'soda-bot',
  label: 'Soda Bot',
  kind: 'character' as const,
  asset: '/assets/cartoon/friends/soda-bot.png',
  side: 'right' as const,
  entrance: 'float' as const,
};

const professor = {
  id: 'professor-thinkwell',
  label: 'Professor Thinkwell',
  kind: 'character' as const,
  asset: '/assets/cartoon/friends/professor-thinkwell.png',
  side: 'right' as const,
  entrance: 'walk' as const,
};

const dinosaur = (id: string, label: string, emoji: string, side: 'left' | 'centre' | 'right' = 'centre') => ({
  id,
  label,
  kind: 'dinosaur' as const,
  emoji,
  side,
  entrance: 'pop' as const,
});

/**
 * A six-minute, 18-scene episode. Dinosaur depictions are intentionally
 * labelled rather than newly illustrated, so the episode only reuses approved
 * Sodafom character artwork until approved dinosaur artwork is supplied.
 */
export const DINOSAUR_ADVENTURE: CartoonEpisodeManifest = {
  id: 'archies-dinosaur-adventure',
  title: "Archie's Dinosaur Adventure",
  ageRange: '5–12',
  targetDurationSeconds: 360,
  subtitleDefault: true,
  engine: {
    contractVersion: '1.0',
    preferredRenderer: 'SOD-CARTOON-ENGINE-22',
    integrationStatus: 'ready-for-agent-22-engine',
  },
  audio: {
    narration: 'browser-or-native-tts',
    founderVoice: 'not-used-no-approved-founder-asset-on-branch',
    music: 'gentle-synth-underscore',
    effects: 'gentle-synth-cues',
  },
  scenes: [
    {
      id: 'time-key',
      title: 'The Time Key',
      durationSeconds: 20,
      setting: 'Sodafom garden at sunset',
      speaker: 'Archie',
      dialogue: 'My golden heart key is glowing! Bella, Soda Bot, shall we see where it leads? Hold on tight — we are travelling a very, very long way into Earth’s past!',
      fact: 'Dinosaurs lived millions of years before people.',
      cast: [archie, bella, sodaBot],
    },
    {
      id: 'mesozoic-map',
      title: 'A Map of Deep Time',
      durationSeconds: 20,
      setting: 'A glowing time-tunnel map',
      speaker: 'Professor Thinkwell',
      dialogue: 'Welcome, explorers! Dinosaurs lived during the Mesozoic Era. It has three big chapters: Triassic, Jurassic and Cretaceous. Today, our key will show us some of its Cretaceous neighbours.',
      fact: 'The Mesozoic Era is often called the age of dinosaurs.',
      cast: [archie, professor, sodaBot],
    },
    {
      id: 'sauropod-valley',
      title: 'Long-Neck Valley',
      durationSeconds: 20,
      setting: 'A fern-filled valley',
      speaker: 'Bella',
      dialogue: 'Look up, Archie! That long-necked sauropod can reach leaves high in the trees. Its huge body needs lots of food, but it is peacefully munching plants.',
      fact: 'Sauropods were a group of long-necked dinosaurs; many ate plants.',
      cast: [archie, bella, dinosaur('sauropod', 'Long-necked sauropod', '🦕')],
    },
    {
      id: 'herbivore-lunch',
      title: 'Leafy Lunch',
      durationSeconds: 20,
      setting: 'The edge of Long-Neck Valley',
      speaker: 'Archie',
      dialogue: 'A dinosaur that eats plants is called a herbivore. Ferns, leaves and other plants are on this dinosaur’s menu — not other animals.',
      fact: 'Herbivore means an animal that eats plants.',
      cast: [archie, dinosaur('sauropod', 'Long-necked sauropod', '🦕')],
      question: {
        prompt: 'Which food would a herbivore choose?',
        choices: ['A leafy branch', 'A fish', 'A steak'],
        answer: 'A leafy branch',
        correctResponse: 'Exactly! A herbivore eats plants.',
        tryAgainResponse: 'Think about the word plant-eater. Try another answer!',
      },
    },
    {
      id: 'stegosaurus',
      title: 'Plates and Spikes',
      durationSeconds: 20,
      setting: 'A sunny rocky clearing',
      speaker: 'Professor Thinkwell',
      dialogue: 'Here is Stegosaurus. It had plates along its back and spikes at the end of its tail. Scientists are still learning exactly what the plates were for, but the tail spikes could help defend it.',
      fact: 'Stegosaurus was a plant-eater with tail spikes.',
      cast: [archie, professor, dinosaur('stegosaurus', 'Stegosaurus', '🦕')],
    },
    {
      id: 'carnivore-clue',
      title: 'A Carnivore Clue',
      durationSeconds: 20,
      setting: 'A quiet forest path',
      speaker: 'Soda Bot',
      dialogue: 'Beep! I found a tooth clue. Sharp, slicing teeth can help an animal eat meat. An animal that eats other animals is called a carnivore.',
      fact: 'Carnivore means an animal that eats other animals.',
      cast: [archie, sodaBot, dinosaur('tooth-clue', 'Fossil tooth clue', '🦷')],
    },
    {
      id: 'trex-watch',
      title: 'T. rex Watch',
      durationSeconds: 20,
      setting: 'A safe time-pod lookout',
      speaker: 'Archie',
      dialogue: 'Wow — Tyrannosaurus rex! We are watching quietly from our safe time-pod. T. rex was a large carnivorous dinosaur that lived late in the Cretaceous Period.',
      fact: 'Tyrannosaurus rex lived in the late Cretaceous Period.',
      cast: [archie, bella, dinosaur('trex', 'Tyrannosaurus rex', '🦖')],
    },
    {
      id: 'diet-detectives',
      title: 'Dinosaur Diet Detectives',
      durationSeconds: 20,
      setting: 'The time-pod science screen',
      speaker: 'Bella',
      dialogue: 'Let’s be diet detectives. Plants for herbivores, and other animals for carnivores. Some dinosaurs may have eaten a mixture, so scientists use clues like teeth and fossilised stomach contents.',
      fact: 'Scientists use evidence such as teeth and fossilised remains to learn about diets.',
      cast: [archie, bella, sodaBot],
      question: {
        prompt: 'Which word means “meat-eater”?',
        choices: ['Carnivore', 'Herbivore', 'Fossil'],
        answer: 'Carnivore',
        correctResponse: 'Yes — a carnivore eats other animals.',
        tryAgainResponse: 'Look for the word that does not mean plant-eater.',
      },
    },
    {
      id: 'triceratops',
      title: 'Three Horns, One Frill',
      durationSeconds: 20,
      setting: 'A riverbank with conifers',
      speaker: 'Professor Thinkwell',
      dialogue: 'Meet Triceratops. Its name means three-horned face. Triceratops and T. rex lived in the same part of North America near the end of the Cretaceous.',
      fact: 'Triceratops was a horned plant-eating dinosaur.',
      cast: [archie, professor, dinosaur('triceratops', 'Triceratops', '🦕')],
    },
    {
      id: 'footprint-trail',
      title: 'Footprints Tell Stories',
      durationSeconds: 20,
      setting: 'A muddy ancient riverbank',
      speaker: 'Archie',
      dialogue: 'These prints became hard in the ground and were later covered up. They can tell scientists how an animal moved, how big its feet were, and sometimes whether it travelled with others.',
      fact: 'Footprints are trace fossils: evidence of an animal’s activity.',
      cast: [archie, sodaBot, dinosaur('footprints', 'Dinosaur footprints', '👣')],
    },
    {
      id: 'fossil-puzzle',
      title: 'The Fossil Puzzle',
      durationSeconds: 20,
      setting: 'A gentle fossil dig',
      speaker: 'Bella',
      dialogue: 'A fossil is a preserved remain or trace of a living thing from long ago. A bone can become fossilised in rock, and a footprint can leave a fossil record too.',
      fact: 'Fossils can be body parts, such as bones, or traces, such as footprints.',
      cast: [archie, bella, dinosaur('fossil', 'Fossil ammonite', '🐚')],
    },
    {
      id: 'palaeontologists',
      title: 'Careful Clue Keepers',
      durationSeconds: 20,
      setting: 'A museum field tent',
      speaker: 'Professor Thinkwell',
      dialogue: 'Palaeontologists study fossils. They record where each clue is found, brush it carefully and compare it with other evidence. A good scientist does not guess — they check.',
      fact: 'Palaeontologists are scientists who study ancient life through fossils.',
      cast: [archie, professor, sodaBot],
    },
    {
      id: 'cretaceous-ending',
      title: 'The World Changes',
      durationSeconds: 20,
      setting: 'The time-pod’s calm sky map',
      speaker: 'Bella',
      dialogue: 'Near the end of the Cretaceous, about 66 million years ago, Earth changed dramatically. Many kinds of plants and animals died out. This is called a mass extinction.',
      fact: 'A mass extinction is when many species die out over a relatively short time in Earth’s history.',
      cast: [archie, bella, sodaBot],
    },
    {
      id: 'asteroid-clue',
      title: 'The Asteroid Clue',
      durationSeconds: 20,
      setting: 'A science-screen view of Earth',
      speaker: 'Professor Thinkwell',
      dialogue: 'Most scientists think a huge asteroid impact was the main cause of the dinosaur mass extinction. It changed the climate quickly. Volcanoes and other changes may have added to the difficult conditions.',
      fact: 'A huge asteroid impact is the leading explanation for the end-Cretaceous mass extinction.',
      cast: [archie, professor, dinosaur('asteroid', 'Asteroid clue', '☄️')],
    },
    {
      id: 'birds',
      title: 'A Dinosaur Surprise',
      durationSeconds: 20,
      setting: 'A bright forest with feather shapes',
      speaker: 'Soda Bot',
      dialogue: 'Important update! Not every dinosaur line ended. Birds are living dinosaurs. When you see a robin, pigeon or owl, you are seeing a very distant dinosaur relative with feathers.',
      fact: 'Birds are the only living dinosaurs.',
      cast: [archie, sodaBot, dinosaur('bird', 'Feathered bird', '🐦')],
    },
    {
      id: 'before-people',
      title: 'Before People',
      durationSeconds: 20,
      setting: 'The time-tunnel homeward path',
      speaker: 'Archie',
      dialogue: 'Dinosaurs and people never met. Dinosaurs lived long before humans appeared. That is why fossils are such brilliant time clues — they help us discover a world nobody could have watched.',
      fact: 'Non-bird dinosaurs were extinct long before humans existed.',
      cast: [archie, bella, sodaBot],
    },
    {
      id: 'fossil-question',
      title: 'Explorer Question',
      durationSeconds: 20,
      setting: 'A glowing fossil gallery',
      speaker: 'Bella',
      dialogue: 'One last explorer question before the key takes us home. Listen for the word that means a clue from life long ago.',
      fact: 'Evidence helps scientists learn about the past.',
      cast: [archie, bella, dinosaur('fossil', 'Fossil clue', '🦴')],
      question: {
        prompt: 'What is a fossil?',
        choices: ['A clue from life long ago', 'A new toy', 'A kind of cloud'],
        answer: 'A clue from life long ago',
        correctResponse: 'Brilliant! Fossils help us learn about ancient life.',
        tryAgainResponse: 'Think about bones, footprints and clues from the past.',
      },
    },
    {
      id: 'home',
      title: 'Dinosaur Detectives',
      durationSeconds: 20,
      setting: 'Sodafom garden at sunrise',
      speaker: 'Archie',
      dialogue: 'We are home! Today we met long-necked sauropods, Stegosaurus, Triceratops and T. rex. We learnt about herbivores, carnivores, fossils and extinction. Keep asking brilliant questions, Dinosaur Detectives!',
      fact: 'Curious questions and careful evidence help us understand prehistoric life.',
      cast: [archie, bella, sodaBot],
    },
  ],
};
