$ vite build && vite build --ssr src/server/entry.ts
Generated an empty chunk: "react-vendor".

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, BookOpen, ChevronLeft, ChevronRight, Eye, Mic, Volume2 } from 'lucide-react';
import { useNavigate } from 'react-router';
import { stopTts, ttsSpeak } from '@/lib/voice-context';
import { motion } from 'motion/react';
import ArchieCharacter from '@/components/ArchieCharacter';

type Story = { title: string; strapline: string; colour: string; pages: string[] };

const STORIES: Story[] = [
  { title: 'Archie and the Magic Key', strapline: 'Believe in yourself', colour: 'from-indigo-600 to-violet-800', pages: [
    'Archie found a little golden key sparkling beneath his pillow.', 'The key had a tiny heart and felt warm in his hand.', 'At breakfast, it pointed towards the old oak tree in the garden.', 'Jessica, Sally and Daisy sniffed a hidden door in the tree trunk.', 'The key opened the door with a friendly click.', 'Inside was a library where every book glowed like a star.', 'A sign said, “Brave readers can open any adventure.”', 'Archie chose a book and read the first word slowly and clearly.', 'The library cheered because Archie had believed in himself.', 'He went home with the key, ready for tomorrow’s adventure.'
  ] },
  { title: 'A Day at the Seaside', strapline: 'Exploring together', colour: 'from-sky-500 to-blue-800', pages: [
    'The sun shone over Felixstowe seafront as Archie packed a picnic.', 'Mum brought sandwiches while Dad carried a bright blue bucket.', 'The dogs raced across the sand, leaving bouncy paw prints.', 'Archie found a smooth shell shaped like a little trumpet.', 'He heard a soft cry near the rocks and followed the sound.', 'A tiny crab was stuck in a plastic ring beside the tide.', 'With a grown-up’s help, Archie gently freed the crab.', 'The crab clicked its claws as if it was saying thank you.', 'Everyone put their litter in the bin and watched the waves sparkle.', 'On the way home, Archie said the best adventures are shared.'
  ] },
  { title: 'The Forest Adventure', strapline: 'Nature is amazing', colour: 'from-emerald-600 to-green-950', pages: [
    'Archie and his family walked into Rendlesham Forest on a windy morning.', 'Tall trees whispered as the dogs trotted along the path.', 'A feather on the ground led them to a tiny bird nest.', 'They stepped back quietly so the parent bird would feel safe.', 'Soon, they found clues: an acorn, a cone and a muddy hoof print.', 'Archie used a picture guide to learn that a deer had passed by.', 'Daisy stopped at a puddle, and everyone laughed at her muddy paws.', 'They listened for a whole minute and heard birds, leaves and a woodpecker.', 'Archie promised to leave the forest just as lovely as they found it.', 'The family walked home with calm hearts and muddy boots.'
  ] },
  { title: 'Archie Helps a Friend', strapline: 'Friends make life brighter', colour: 'from-orange-500 to-rose-700', pages: [
    'At football club, Archie noticed that Amir was sitting quietly by himself.', 'Amir said he was worried because he had missed an easy goal.', 'Archie told him everyone makes mistakes while they are learning.', 'They practised passing slowly, one kind kick at a time.', 'Sally chased the ball and made everybody laugh.', 'Amir tried again and this time his pass reached Archie perfectly.', 'The coach praised their teamwork, not just the score.', 'Archie said, “You did not give up. That is what brave means.”', 'Amir smiled and invited another child to join their practice.', 'By home time, the team had learned that kindness makes friends stronger.'
  ] },
  { title: 'The Lost Puppy', strapline: 'Kindness always wins', colour: 'from-amber-500 to-orange-800', pages: [
    'On a walk near the harbour, Archie heard a small bark behind a bench.', 'A fluffy puppy with a red collar was shivering under a coat.', 'Archie stayed calm and asked Dad to help instead of chasing it.', 'They read the name “Milo” on the puppy’s tag.', 'Dad phoned the number while Mum wrapped Milo in a warm towel.', 'Jessica and Sally sat nearby, showing Milo he was safe.', 'Soon a worried family hurried along the path calling his name.', 'Milo wagged so hard that his whole body wriggled.', 'His family thanked Archie for being careful and kind.', 'Archie waved goodbye, knowing small helpful actions can mean a lot.'
  ] },
  { title: 'A Visit to Orford Castle', strapline: 'History comes to life', colour: 'from-stone-500 to-slate-800', pages: [
    'Archie saw Orford Castle rising above the green grass like a giant sandcastle.', 'Inside, a guide explained that people had lived there hundreds of years ago.', 'Archie climbed the winding stairs slowly, counting every step.', 'From the top, he could see the river, boats and tiny roofs below.', 'He imagined a medieval cook stirring a huge pot for hungry visitors.', 'Kayla spotted narrow windows made for watching the castle grounds.', 'The family read old maps and looked for the shape of the keep.', 'Archie drew the castle in his notebook with three tall towers.', 'He learned that asking questions helps history feel alive.', 'At sunset, the castle looked golden and Archie promised to visit again.'
  ] },
  { title: 'Space Explorers', strapline: 'Reach for the stars', colour: 'from-blue-700 to-indigo-950', pages: [
    'One clear night, Archie pointed his telescope at the moon.', 'The Magic Key glowed and turned the telescope into a starship window.', 'Archie and Soda Bot floated gently above the blue Earth.', 'They saw that the planet has oceans, clouds and one bright moon.', 'A friendly astronaut explained why astronauts wear special space suits.', 'They watched the International Space Station travel quietly overhead.', 'Archie learned that the sun is a star and our solar system is enormous.', 'Before leaving, he checked that every bit of rubbish was safely stored.', 'The starship brought him home just as Mum called him for bed.', 'Archie looked up and knew that curious questions can travel very far.'
  ] },
  { title: 'Animals Around the World', strapline: 'Our wonderful world', colour: 'from-teal-500 to-emerald-800', pages: [
    'Archie opened a pop-up map and animals began to wave from every continent.', 'An elephant showed him how big ears help it stay cool in Africa.', 'A penguin waddled from Antarctica and explained its warm waterproof feathers.', 'A red panda climbed high in an Asian forest with its fluffy tail.', 'A kangaroo bounced across Australia with a joey peeking from its pouch.', 'In South America, a sloth moved slowly through the treetops.', 'Archie noticed that every animal needed a safe home, food and clean water.', 'He and his friends made a poster saying, “Be kind to animal homes.”', 'The animals thanked Archie with a cheerful parade around the map.', 'He closed the book knowing that our world is full of amazing neighbours.'
  ] },
  { title: 'Healthy and Happy', strapline: 'Move, play and be you', colour: 'from-lime-500 to-green-800', pages: [
    'Archie woke up feeling a little sleepy and slow.', 'Mum reminded him to drink water and eat a colourful breakfast.', 'He chose fruit, toast and yoghurt, then felt ready to move.', 'Outside, Archie tried ten gentle star jumps with Daisy watching closely.', 'When he felt puffed, he stopped for a calm rest and a deep breath.', 'At school, he learned that feelings are important too.', 'He told a trusted grown-up that he was nervous about a big spelling test.', 'Together they made a small plan: practise, rest and try his best.', 'After school, Archie played, laughed and went to bed at a good time.', 'He learned that being healthy means caring for body, mind and feelings.'
  ] },
  { title: 'Caring for Our Planet', strapline: 'Small steps make a big difference', colour: 'from-cyan-500 to-green-800', pages: [
    'Archie saw a paper wrapper blowing along the park path.', 'He picked it up safely and put it in the right bin.', 'The Magic Key showed him a picture of the Earth smiling brightly.', 'At home, Archie helped sort paper, tins and bottles for recycling.', 'Dad fixed a dripping tap while Archie placed a bucket underneath.', 'Mum showed him how to turn off lights in empty rooms.', 'The family planted wildflower seeds for bees and butterflies.', 'Soon, a bee landed nearby and buzzed around the new flowers.', 'Archie told his friends that nobody has to be perfect to help the planet.', 'The Earth in the key shone again: small kind choices add up.'
  ] },
];

export default function ArchieStoryCollectionPage() {
  const navigate = useNavigate();
  const [storyIndex, setStoryIndex] = useState<number | null>(null);
  const [page, setPage] = useState(0);
  const [turning, setTurning] = useState(false);
  const [archiesView, setArchiesView] = useState(false);
  const [listening, setListening] = useState(false);
  const [wordStates, setWordStates] = useState<Array<'pending' | 'correct' | 'wrong'>>([]);
  const [wordIndex, setWordIndex] = useState(0);
  const [welcome, setWelcome] = useState(false);
  const recognitionRef = useRef<any>(null);
  const story = storyIndex === null ? null : STORIES[storyIndex];

  useEffect(() => () => stopTts(), []);
  const words = story ? story.pages[page].split(/\s+/) : [];
  const clean = (word: string) => word.toLowerCase().replace(/[^a-z0-9']/g, '');
  const resetReadAlong = () => { recognitionRef.current?.stop?.(); setListening(false); setWordStates(words.map(() => 'pending')); setWordIndex(0); };
  const open = (index: number) => { setStoryIndex(index); setPage(0); setWelcome(true); setWordStates(STORIES[index].pages[0].split(/\s+/).map(() => 'pending')); setWordIndex(0); };
  const close = () => { resetReadAlong(); stopTts(); setStoryIndex(null); };
  const changePage = (next: number) => { if (!story || turning) return; const safe = Math.max(0, Math.min(story.pages.length - 1, next)); if (safe === page) return; resetReadAlong(); setTurning(true); window.setTimeout(() => { setPage(safe); setWordStates(story.pages[safe].split(/\s+/).map(() => 'pending')); setWordIndex(0); setTurning(false); }, 750); };
  const startReading = () => {
    if (!story) return;
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) { ttsSpeak('Your browser does not support reading aloud yet.'); return; }
    const recognition = new SpeechRecognition(); recognition.lang = 'en-GB'; recognition.continuous = false; recognition.interimResults = false;
    recognition.onresult = (event: any) => {
      const heard = String(event.results[event.results.length - 1][0].transcript).split(/\s+/).map(clean).filter(Boolean);
      let position = wordIndex; const nextStates = [...(wordStates.length ? wordStates : words.map(() => 'pending' as const))];
      for (const spoken of heard) { if (position >= words.length) break; if (spoken === clean(words[position])) { nextStates[position] = 'correct'; position += 1; } else { nextStates[position] = 'wrong'; ttsSpeak(`Let us sound this out together: ${words[position]}`); break; } }
      setWordStates(nextStates); setWordIndex(position); setListening(false);
      if (position >= words.length && page < 9) window.setTimeout(() => changePage(page + 1), 1100);
    };
    recognition.onerror = () => setListening(false); recognition.onend = () => setListening(false); recognitionRef.current = recognition; setListening(true); recognition.start();
  };

  if (story && welcome) return <main className={`min-h-screen bg-gradient-to-b ${story.colour} px-4 py-5 text-slate-950`}><div className="mx-auto max-w-4xl"><button onClick={close} className="mb-4 flex min-h-12 items-center gap-2 rounded-full bg-white px-5 font-black shadow-xl"><ArrowLeft /> Back to shelf</button><motion.section initial={{ scale: .75, opacity: 0, rotateY: -55 }} animate={{ scale: 1, opacity: 1, rotateY: 0 }} transition={{ type: 'spring', stiffness: 115, damping: 17 }} className="relative overflow-hidden rounded-[2.5rem] border-8 border-amber-200 bg-slate-900 shadow-2xl"><img src="/assets/stories/archie-library-welcome.jpg" alt="Archie and his dogs waiting in the magical library" className="h-[520px] w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/85 via-transparent to-transparent" /><motion.div className="absolute bottom-8 left-7" animate={{ y: [0, -6, 0], scale: [1, 1.03, 1] }} transition={{ duration: 1.5, repeat: Infinity }}><ArchieCharacter size={116} speaking /></motion.div><motion.span className="absolute bottom-12 right-12 text-6xl" initial={{ x: 180, opacity: 0 }} animate={{ x: 0, opacity: 1 }} transition={{ duration: 1.2 }}>🧒</motion.span><motion.span className="absolute left-[68%] top-[19%] text-5xl" animate={{ y: [0, 260], rotate: [0, 35, 90] }} transition={{ duration: 3.5, repeat: Infinity, repeatDelay: 2 }}>📚</motion.span><div className="absolute inset-x-0 bottom-0 p-7 text-white"><p className="text-2xl font-black sm:text-3xl">Come and sit down, friend! Let’s look at the book together.</p><p className="mt-2 max-w-xl font-bold text-white/90">The dogs wiggle, Archie’s lips move, and the storybook sparkles before you step into the adventure.</p><button onClick={() => setWelcome(false)} className="mt-5 min-h-12 rounded-full bg-yellow-300 px-6 font-black text-purple-950 shadow-xl">Let’s look at the book ✨</button></div></motion.section></div></main>;

  if (story) return <main className={`min-h-screen bg-gradient-to-b ${story.colour} px-4 py-5 text-slate-950`}>
    <div className="mx-auto max-w-4xl">
      <button onClick={close} className="mb-4 flex min-h-12 items-center gap-2 rounded-full bg-white px-5 font-black shadow-xl"><ArrowLeft /> Back to shelf</button>
      <motion.article initial={{ rotateY: -80, scale: .72, opacity: 0 }} animate={{ rotateY: 0, scale: 1, opacity: 1 }} transition={{ type: 'spring', stiffness: 115, damping: 18 }} className="overflow-hidden rounded-[2rem] border-8 border-amber-200 bg-[#fff9e8] shadow-2xl">
        <div className="grid min-h-[620px] md:grid-cols-2">
          <div className="relative min-h-72 overflow-hidden bg-indigo-950"><motion.img key={`${story.title}-${page}-${archiesView}`} src="/assets/approved/stories.png" alt="Archie’s illustrated storybook shelf" className="absolute inset-0 h-full w-full object-cover object-center" initial={{ scale: archiesView ? 1.42 : 1.16, x: page % 2 ? '5%' : '-5%', opacity: .55 }} animate={{ scale: archiesView ? 1.26 : 1.04, x: archiesView ? (page % 2 ? '-13%' : '13%') : (page % 2 ? '-3%' : '3%'), opacity: 1 }} transition={{ duration: 7, ease: 'linear' }} /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/45 to-transparent" />{[0, 1, 2, 3, 4].map((star) => <motion.span key={star} className="absolute h-3 w-3 rounded-full bg-yellow-200 shadow-[0_0_16px_5px_rgba(253,224,71,.9)]" initial={{ left: `${12 + star * 18}%`, top: '88%', opacity: 0 }} animate={{ top: '10%', opacity: [0, 1, 1, 0], scale: [0.4, 1.2, .8] }} transition={{ duration: 3.5 + star * .4, delay: star * .3, repeat: Infinity }} />)}<motion.div className="absolute bottom-5 left-5 h-16 w-16 rounded-full border-4 border-yellow-200 bg-amber-400 shadow-[0_0_32px_9px_rgba(250,204,21,.8)]" animate={{ rotate: 360, scale: [1, 1.16, 1] }} transition={{ rotate: { duration: 9, repeat: Infinity, ease: 'linear' }, scale: { duration: 1.8, repeat: Infinity } }} />{!archiesView && <><motion.div className="absolute bottom-2 left-2" animate={turning ? { x: ['0%', '290%'], rotate: [0, -8, 8, 0] } : { y: [0, -7, 0], rotate: [0, -2, 2, 0] }} transition={turning ? { duration: .7, ease: 'easeInOut' } : { duration: 2.2, repeat: Infinity }}><ArchieCharacter size={96} speaking={turning} /></motion.div><motion.img src="/assets/cartoon/friends/daisy.png" alt="Daisy the dog" className="absolute bottom-3 right-4 h-20 w-20 object-contain drop-shadow-xl" animate={turning ? { x: ['0%', '-300%'], rotate: [0, 10, -10, 0] } : { y: [0, -8, 0], rotate: [-3, 3, -3] }} transition={turning ? { duration: .65, ease: 'easeInOut' } : { duration: 1.8, repeat: Infinity }} /></>}<div className="absolute bottom-4 left-4 rounded-full bg-white/90 px-4 py-2 font-black">{archiesView ? '👀 Looking through Archie’s eyes' : '✨ Moving illustrated story page'}</div></div>
          <div className="flex flex-col justify-between p-7 sm:p-10"><div><p className="text-sm font-black uppercase tracking-widest text-purple-700">Archie’s Stories · Page {page + 1} of 10</p><h1 className="mt-2 font-serif text-3xl font-black text-purple-950 sm:text-5xl">{story.title}</h1><p className="mt-8 font-serif text-2xl leading-relaxed text-slate-800 sm:text-3xl">{words.map((word, index) => <span key={`${page}-${index}`} className={wordStates[index] === 'correct' ? 'text-green-600' : wordStates[index] === 'wrong' ? 'text-red-600 underline decoration-red-500 decoration-2' : 'text-slate-900'}>{word}{' '}</span>)}</p><p className="mt-3 text-sm font-bold text-purple-700">{listening ? '🎙️ Archie is listening…' : wordIndex === words.length && words.length > 0 ? '⭐ Brilliant reading!' : 'Black = to read · Green = correct · Red = Archie will help'}</p></div><div className="mt-8 flex flex-wrap items-center justify-between gap-3"><button onClick={() => ttsSpeak(story.pages[page])} className="flex min-h-12 items-center gap-2 rounded-full bg-purple-700 px-5 font-black text-white"><Volume2 /> Read to me</button><button onClick={startReading} disabled={listening || wordIndex === words.length} className="flex min-h-12 items-center gap-2 rounded-full bg-emerald-600 px-5 font-black text-white disabled:opacity-50"><Mic /> {listening ? 'Listening…' : wordIndex === words.length ? 'Page completed' : 'I want to read'}</button><button onClick={() => setArchiesView(value => !value)} className="flex min-h-12 items-center gap-2 rounded-full bg-sky-600 px-5 font-black text-white"><Eye /> {archiesView ? 'Leave Archie’s view' : 'Look through Archie’s eyes'}</button><div className="flex gap-2"><button disabled={page === 0 || turning} onClick={() => changePage(page - 1)} className="rounded-full bg-amber-300 p-3 font-black disabled:opacity-40"><ChevronLeft /></button><button disabled={page === 9 || turning} onClick={() => changePage(page + 1)} className="rounded-full bg-amber-300 p-3 font-black disabled:opacity-40"><ChevronRight /></button></div></div></div>
        </div>
      </motion.article>
    </div>
  </main>;

  return <main className="min-h-screen bg-gradient-to-b from-amber-100 via-orange-100 to-sky-200 px-4 py-5 text-slate-950"><div className="mx-auto max-w-6xl"><div className="mb-5 flex items-center justify-between gap-3"><button onClick={() => navigate('/reading')} className="flex min-h-12 items-center gap-2 rounded-full bg-white px-5 font-black shadow-xl"><ArrowLeft /> Reading</button><h1 className="text-center text-2xl font-black text-purple-950 sm:text-4xl">📚 ARCHIE’S BOOK COLLECTION</h1><span className="w-24" /></div><section className="relative overflow-hidden rounded-[2rem] border-8 border-amber-800 bg-amber-900 shadow-2xl"><img src="/assets/approved/stories.png" alt="Archie’s Stories book shelf" className="w-full border-b-8 border-amber-800" /><motion.div className="absolute left-[28%] top-[30%]" animate={{ y: [0, -6, 0], rotate: [-2, 2, -2] }} transition={{ duration: 2.1, repeat: Infinity }}><ArchieCharacter size={62} /></motion.div><motion.img src="/assets/cartoon/friends/daisy.png" alt="Daisy balancing safely on the shelf" className="absolute left-[48%] top-[39%] h-14 w-14 object-contain" animate={{ rotate: [-5, 5, -5], y: [0, -5, 0] }} transition={{ duration: 1.6, repeat: Infinity }} /><div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-5">{STORIES.map((item, index) => <button key={item.title} onClick={() => open(index)} className={`min-h-48 rounded-2xl bg-gradient-to-br ${item.colour} p-4 text-left text-white shadow-lg transition hover:-translate-y-1 active:scale-95`}><BookOpen size={32} /><h2 className="mt-6 text-xl font-black">{item.title}</h2><p className="mt-2 text-sm font-bold text-white/85">{item.strapline}</p><span className="mt-4 inline-block rounded-full bg-white/20 px-3 py-1 text-xs font-black">Open book</span></button>)}</div></section><p className="mt-4 text-center font-bold text-slate-700">Tap a book, then use “Read to me” or the arrows to turn all ten pages.</p></div></main>;
}
