import {useEffect,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import './app-screen.css';
/** Flow lengthy pages onto horizontal app screens rather than shrinking text. */
export default function AppScreenPager({children}:{children:ReactNode}){
 const viewport=useRef<HTMLDivElement>(null);const flow=useRef<HTMLDivElement>(null);const [page,setPage]=useState(0);const [count,setCount]=useState(1);const [width,setWidth]=useState(0);
 useLayoutEffect(()=>{const box=viewport.current;if(!box)return;const update=()=>setWidth(box.clientWidth);update();const ro=typeof ResizeObserver==='undefined'?null:new ResizeObserver(update);ro?.observe(box);window.addEventListener('resize',update);return()=>{ro?.disconnect();window.removeEventListener('resize',update);};},[]);
 useEffect(()=>{const inner=flow.current;if(!inner||!width)return;const update=()=>{const total=Math.max(1,Math.ceil((inner.scrollWidth+1)/(width+16)));setCount(total);setPage(p=>Math.min(p,total-1));};update();const ro=typeof ResizeObserver==='undefined'?null:new ResizeObserver(update);ro?.observe(inner);const mo=new MutationObserver(update);mo.observe(inner,{childList:true,subtree:true,characterData:true});return()=>{ro?.disconnect();mo.disconnect();};},[width,children]);
 return <div className="app-screen-pager"><div ref={viewport} className="app-screen-window"><div ref={flow} className="app-screen-flow" style={{columnWidth:width||undefined,transform:`translateX(-${page*(width+16)}px)`}} onFocusCapture={event=>{const element=event.target as HTMLElement;const box=viewport.current;if(!box)return;const x=element.getBoundingClientRect().left-box.getBoundingClientRect().left+page*(width+16);setPage(Math.max(0,Math.min(count-1,Math.floor(x/(width+16)))));}}>{children}</div></div><nav className="app-screen-controls" aria-label="Page screens"><button type="button" disabled={page===0} onClick={()=>setPage(p=>p-1)}>← Previous</button><span aria-live="polite">{page+1} / {count}</span><button type="button" disabled={page>=count-1} onClick={()=>setPage(p=>p+1)}>Next →</button></nav></div>;
}
