import {useEffect,useLayoutEffect,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import './app-screen.css';
/** Flow lengthy pages onto horizontal app screens rather than shrinking text. */
export default function AppScreenPager({children}:{children:ReactNode}){
 const viewport=useRef<HTMLDivElement>(null);const flow=useRef<HTMLDivElement>(null);const pointerDown=useRef(false);const pageRef=useRef(0);const [page,setPage]=useState(0);const [count,setCount]=useState(1);const [width,setWidth]=useState(0);
 const resetNativeScroll=()=>{if(viewport.current)viewport.current.scrollLeft=0;};
 const showPage=(next:(current:number)=>number)=>{resetNativeScroll();setPage(current=>{const value=next(current);pageRef.current=value;return value;});viewport.current?.ownerDocument.defaultView?.scrollTo({top:0,left:0,behavior:'auto'});};
 const showElement=(element:HTMLElement)=>{const align=()=>{const box=viewport.current,inner=flow.current;if(!box||!inner)return;const controller=element.closest<HTMLElement>('[aria-controls]');const controlledId=controller?.getAttribute('aria-controls');const controlled=controlledId?inner.ownerDocument.getElementById(controlledId):null;const target=controlled&&inner.contains(controlled)?controlled:element;const stride=(box.clientWidth||width)+16;const x=target.getBoundingClientRect().left-box.getBoundingClientRect().left+pageRef.current*stride+box.scrollLeft;const liveCount=Math.max(1,Math.ceil((inner.scrollWidth+1)/stride));const value=Math.max(0,Math.min(liveCount-1,Math.round(x/stride)));resetNativeScroll();pageRef.current=value;setPage(value);};align();const view=viewport.current?.ownerDocument.defaultView;view?.requestAnimationFrame(()=>view.requestAnimationFrame(align));};
 useLayoutEffect(()=>{const box=viewport.current;if(!box)return;const update=()=>setWidth(box.clientWidth);update();const ro=typeof ResizeObserver==='undefined'?null:new ResizeObserver(update);ro?.observe(box);window.addEventListener('resize',update);return()=>{ro?.disconnect();window.removeEventListener('resize',update);};},[]);
 useEffect(()=>{const inner=flow.current;if(!inner||!width)return;const update=()=>{const total=Math.max(1,Math.ceil((inner.scrollWidth+1)/(width+16)));setCount(total);setPage(p=>{const value=Math.min(p,total-1);pageRef.current=value;return value;});};update();const ro=typeof ResizeObserver==='undefined'?null:new ResizeObserver(update);ro?.observe(inner);const mo=new MutationObserver(update);mo.observe(inner,{childList:true,subtree:true,characterData:true});return()=>{ro?.disconnect();mo.disconnect();};},[width,children]);
 return <div className="app-screen-pager"><div ref={viewport} className="app-screen-window"><div ref={flow} className="app-screen-flow" style={{columnWidth:width||undefined,'--app-screen-width':width?`${width}px`:undefined,transform:`translateX(-${page*(width+16)}px)`} as CSSProperties} onPointerDownCapture={()=>{pointerDown.current=true;}} onPointerUpCapture={()=>{pointerDown.current=false;}} onPointerCancelCapture={()=>{pointerDown.current=false;}} onClickCapture={event=>{const element=event.target as HTMLElement;const anchor=element.closest('a');const href=anchor?.getAttribute('href');if(href?.startsWith('#')){const target=flow.current?.ownerDocument.getElementById(href.slice(1));if(!target||!flow.current?.contains(target))return;event.preventDefault();showElement(target);viewport.current?.ownerDocument.defaultView?.scrollTo({top:0,left:0,behavior:'auto'});return;}showElement(element);}} onFocusCapture={event=>{if(!pointerDown.current)showElement(event.target as HTMLElement);}}>{children}</div></div><nav className="app-screen-controls" aria-label="Page screens"><button type="button" disabled={page===0} onClick={()=>showPage(p=>p-1)}>← Previous</button><span role="status" aria-live="polite" aria-atomic="true"><span aria-hidden="true">{page+1} / {count}</span><span className="sr-only">Screen {page+1} of {count}</span></span><button type="button" disabled={page>=count-1} onClick={()=>showPage(p=>p+1)}>Next →</button></nav></div>;
}
